spring.application.name=ProductCatalogService

fakeStoreUrl=${FAKE_STORE_URL}
userServiceUrl=${USER_SERVICE_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka